name: Build

on:
  push:
    branches: ['master']
  schedule:
    - cron: '20 2 * * *'

jobs:
  build-amd64-linux:
    runs-on: nix-amd64

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Cache Login
      run: |
        echo "Logging in ..."
        attic login --set-default attic ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
    - run: |
        nix build '.#anonymous-overflow'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#bulk-downloader-for-reddit'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#fennel-ls'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#headscale-ui'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#lexical'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#neovim-nightly'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#q'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#rimgo'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#rexit'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#vuetorrent'
        attic push ${{ secrets.ATTIC_CACHE }} ./result

  build-arm64-linux:
    runs-on: nix-arm64

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Cache Login
      run: |
        echo "Logging in ..."
        attic login --set-default attic ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
    - run: |
        nix build '.#fennel-ls'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#lexical'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#neovim-nightly'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#q'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - run: |
        nix build '.#weewx-proxy'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
