name: Build

on:
  push:
    branches: ['master']
  schedule:
    - cron: '20 2 * * *'

jobs:
  build-amd64-linux:
    runs-on: nix-amd64

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Cache Login
      run: |
        echo "Logging in ..."
        attic login --set-default attic ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
    - name: Build anonymous-overflow
      run: |
        nix build '.#anonymous-overflow'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build bulk-downloader-for-reddit
      run: |
        nix build '.#bulk-downloader-for-reddit'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build fennel-ls
      run: |
        nix build '.#fennel-ls'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build headscale-ui
      run: |
        nix build '.#headscale-ui'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build lexical
      run: |
        nix build '.#lexical'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build neovim-nightly
      run: |
        nix build '.#neovim-nightly'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build q
      run: |
        nix build '.#q'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build redlib
      run: |
        nix build '.#redlib'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build rimgo
      run: |
        nix build '.#rimgo'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build rexit
      run: |
        nix build '.#rexit'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build vuetorrent
      run: |
        nix build '.#vuetorrent'
        attic push ${{ secrets.ATTIC_CACHE }} ./result

  build-arm64-linux:
    runs-on: nix-arm64

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Cache Login
      run: |
        echo "Logging in ..."
        attic login --set-default attic ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
    - name: Build fennel-ls
      run: |
        nix build '.#fennel-ls'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build lexical
      run: |
        nix build '.#lexical'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build neovim-nightly
      run: |
        nix build '.#neovim-nightly'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build q
      run: |
        nix build '.#q'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
    - name: Build weewx-proxy
      run: |
        nix build '.#weewx-proxy'
        attic push ${{ secrets.ATTIC_CACHE }} ./result
