name: Update Flake

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-flake:
    runs-on: nix-amd64

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - run: nix flake update
    - name: Update packages
      run: |
        nix-update --flake anonymous-overflow
        nix-update --flake --version development bulk-downloader-for-reddit
        nix-update --flake q
        nix-update --flake redlib 
        env NIX_PATH=nixpkgs=$(nix flake metadata github:nixos/nixpkgs/nixos-unstable-small --json | jq -r .path) nix-shell ./packages/tabnine/update.sh
        nix-update --flake tg-archive
        nix-update --flake vuetorrent
    - uses: https://github.com/stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[automation] Update flake"
        commit_user_name: Actions Bot
        commit_user_email: daniel+actions-bot@kempkens.io
        commit_author: Actions Bot <daniel+actions-bot@kempkens.io>
