name: Update Flake

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-flake:
    runs-on: nix-amd64

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - run: nix flake update
    - name: Update packages
      run: |
        nix-update --flake ai-robots-txt
        nix-update --flake anonymous-overflow
        nix-update --flake --version branch=development bulk-downloader-for-reddit
        nix-update --flake controld
        nix-update --flake discord-downloader-go
        nix-update --flake octodns-desec
        nix-update --flake octodns-ovh
        nix-update --flake q
        nix-update --flake --version branch slurp-gts
        nix-update --flake tg-archive
        nix-update --flake --version branch=main torrent-best-blocklist
        #nix-update --flake --version branch tuwunel
        nix-update --flake vuetorrent
    - uses: https://github.com/stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[automation] Update flake"
        commit_user_name: Actions Bot
        commit_user_email: daniel+actions-bot@kempkens.io
        commit_author: Actions Bot <daniel+actions-bot@kempkens.io>
