name: Build

on:
  push:
    branches: ['master']
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch:

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#anonymous-overflow'
    - run: nix build '.#fennel-ls'
    - run: nix build '.#luarocks-jsregexp'
    - run: nix build '.#nitter-unstable'
    - run: nix build '.#q'
    - run: nix build '.#website-docs-nifoc-pw'

  build-x86_64-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#cliclick'
    - run: nix build '.#fennel-ls'
    - run: nix build '.#luarocks-jsregexp'
    - run: nix build '.#phantomjs'
    - run: nix build '.#q'
