name: Build

on:
  push:
    branches: ['master']

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#proximity-sort'
    - run: nix build '.#q'

  build-x86_64-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#cliclick'
    - run: nix build '.#phantomjs'
    - run: nix build '.#proximity-sort'
    - run: nix build '.#q'
