name: Update Flake

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - run: nix flake update
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[automation] Update flake"
